Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-5, pull requests merged in 2025-09, with the labels that each got.

#75 [style] 헤더 폰트 사이즈 변경
  src/shared/components/header/Header.tsx
Labels: style

#83 가계부 설정 삭제, 초대, 수정하기 기능
  src/app/Router.tsx
  src/features/accountbook/setting/service/service.ts
  src/features/accountbook/setting/ui/AccountBookCard.tsx
  src/features/accountbook/setting/ui/ServiceCard.tsx
  src/features/accountbook/setting/ui/deleteGroup/DeleteModal.tsx
  src/features/group/GroupCard.tsx
  src/features/group/InviteInput.tsx
  src/features/group/ThisMonthCard.tsx
  src/features/group/UserList.tsx
  src/features/group/create/GroupName.tsx
  src/features/group/create/Invite.tsx
  src/features/group/create/InviteList.tsx
  src/features/group/create/hook/useCreateGroup.ts
  src/features/group/edit/EditLayout.tsx
  src/features/group/edit/invitation/Invitation.tsx
  src/features/group/edit/invitation/InviteCompleteBtn.tsx
  src/features/group/edit/invitation/InvitedList.tsx
  src/shared/components/modal/ConfirmModal.tsx
  src/shared/components/snackbar/Snackbar.tsx
  src/shared/stores/useGroupStore.ts
  src/shared/stores/useSnackbarStore.ts
Labels: feat, style

#89 feat/회원탈퇴
  .vscode/extensions.json
  src/features/accountbook/setting/ui/deleteGroup/DeleteModal.tsx
  src/features/login/LoginCard.tsx
  src/features/more/ResignBtn.tsx
  src/pages/accountbook/SettingPage.tsx
  src/pages/more/More.tsx
  src/shared/assets/loading.gif
  src/shared/assets/spinner.png
  src/shared/components/layout/Layout.tsx
  src/shared/components/loading/Loading.tsx
  src/shared/components/snackbar/Snackbar.tsx
  supabase/.gitignore
  supabase/config.toml
  supabase/functions/delete-user/.npmrc
  supabase/functions/delete-user/deno.json
  supabase/functions/delete-user/index.ts
Labels: feat

#102 가계부 홈 스타일 수정
  src/features/group/GroupCard.tsx
  src/features/group/Name.tsx
  src/features/group/ThisMonthCard.tsx
  src/pages/group/Home.tsx
Labels: style

#109 리팩토링 & 터치 이벤트
  src/features/accountbook/setting/ui/ServiceCard.tsx
  src/features/group/GroupCard.tsx
  src/features/group/InviteInput.tsx
  src/features/group/create/GroupName.tsx
  src/features/group/create/hook/useCreateGroup.ts
  src/features/group/edit/EditGroup.tsx
  src/pages/group/CreateGroup.tsx
  src/pages/more/More.tsx
Labels: refactor
